"""integrate Cloudinary for image uploads and update environment configuration

Revision ID: 00a11fcab7a6
Revises: 8b631f940077
Create Date: 2026-07-20 14:40:19.753082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a11fcab7a6'
down_revision = '8b631f940077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
