"""init

Revision ID: 0b998320bcb9
Revises: 9a7c4f1b2e03
Create Date: 2026-07-17 11:41:13.245738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b998320bcb9'
down_revision = '9a7c4f1b2e03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
