"""Make order_id nullable in payments

Revision ID: 2de04131e76f
Revises: 62ae9aef25b9
Create Date: 2026-07-21 16:05:04.591058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de04131e76f'
down_revision = '62ae9aef25b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
