"""init

Revision ID: 3fca355049cc
Revises: e7a4bf44cb53
Create Date: 2026-07-21 15:57:47.324839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fca355049cc'
down_revision = 'e7a4bf44cb53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
