"""add_addresses_table

Revision ID: 59096ea3755c
Revises: d539ef1b9bda
Create Date: 2026-07-22 10:56:14.149857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59096ea3755c'
down_revision = 'd539ef1b9bda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
