"""init

Revision ID: 668268f31c6a
Revises: b528ace55a87
Create Date: 2026-07-16 12:24:55.574762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668268f31c6a'
down_revision = 'b528ace55a87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
