"""init

Revision ID: 6b34e6599940
Revises: bbf34bc6f080
Create Date: 2026-07-13 12:05:16.375298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b34e6599940'
down_revision = 'bbf34bc6f080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
