"""init

Revision ID: 91688b9b074e
Revises: 08b7e92954a1
Create Date: 2026-07-13 13:56:29.643272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91688b9b074e'
down_revision = '08b7e92954a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
