"""Add cascade delete to cart and wishlist

Revision ID: b528ace55a87
Revises: 12f6c9a2b8d4
Create Date: 2026-07-16 11:22:14.091072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b528ace55a87'
down_revision = '12f6c9a2b8d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_items_product_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('wishlist_items_product_id_fkey', 'wishlist_items', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist_items', type_='foreignkey')
    op.create_foreign_key('wishlist_items_product_id_fkey', 'wishlist_items', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_product_id_fkey', 'cart_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
