"""add_notification_table

Revision ID: e7a4bf44cb53
Revises: c53b101fc089
Create Date: 2026-07-20 18:44:26.231163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a4bf44cb53'
down_revision = 'c53b101fc089'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
